### ISSUE TITLE
Deployments with ready replicas are reported as unavailable

### ISSUE THREAD

**Issue by andrew-farries** [cjheppell/kondition#1]
Kondition will report a deployment as 'unavailable' even if it has some ready replicas.

The condition for deployment readiness:

https://github.com/cjheppell/kondition/blob/20b5bf772c71a7981bb703440feeb41cc0c3f02a/internal/kubernetes/statusclient.go#L56

Requires **all** replicas in the deployment to be ready. This is probably too strict.

The problem can be reproduced with this deployment:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: busybox
  name: busybox
spec:
  replicas: 5
  selector:
    matchLabels:
      app: busybox
  strategy: {}
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - image: busybox
        name: busybox
        command:
        - sh
        - -c
        args:
        - 'while [[ true ]]; do touch foo; sleep $(($RANDOM % 10 + 3)); rm foo; sleep $(($RANDOM % 10 + 3)); done'
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 1
          exec:
            command: ['cat', 'foo']
```

This creates a deployment whose number of ready replicas will fluctuate between 0 and 5. Kondition will report the deployment as unavailable unless all 5 replicas are ready.

One solution to this would be to allow the minimum number of ready replicas for a deployment to be specified via `services.yaml`.
